server:
  host: "localhost"
  port: "4000"
  readTimeout: 5      # seconds
  writeTimeout: 10    # seconds
  idleTimeout: 60     # seconds
  maxUpload: 1        # Mbytes
  uploadMIMETypes:
    - "text/plain"